# Generated by Django 6.0.3 on 2026-04-05 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('pickup_location', models.CharField(choices=[('airport', 'Airport'), ('railway', 'Railway Station'), ('bus_stand', 'Bus Stand'), ('city_center', 'City Center'), ('mall', 'Shopping Mall'), ('hotel', 'Hotel'), ('other', 'Other')], max_length=100)),
                ('return_location', models.CharField(choices=[('airport', 'Airport'), ('railway', 'Railway Station'), ('bus_stand', 'Bus Stand'), ('city_center', 'City Center'), ('mall', 'Shopping Mall'), ('hotel', 'Hotel'), ('other', 'Other')], max_length=100)),
                ('custom_pickup_location', models.CharField(blank=True, help_text="For 'Other' location", max_length=255)),
                ('custom_return_location', models.CharField(blank=True, help_text="For 'Other' location", max_length=255)),
                ('total_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_helmet_required', models.BooleanField(default=True)),
                ('insurance_opted', models.BooleanField(default=False)),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bikes.bike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='bookings_bo_user_id_69a5d5_idx'), models.Index(fields=['start_date', 'end_date'], name='bookings_bo_start_d_8ecf7f_idx')],
            },
        ),
    ]
