# Generated by Django 6.0.3 on 2026-04-05 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bike_type', models.CharField(choices=[('MTB', 'Mountain Bike'), ('Road', 'Road Bike'), ('Hybrid', 'Hybrid Bike'), ('Cruiser', 'Cruiser Bike'), ('BMX', 'BMX Bike'), ('Electric', 'Electric Bike')], max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=2024, validators=[django.core.validators.MinValueValidator(2000)])),
                ('city', models.CharField(choices=[('Delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('Bangalore', 'Bangalore'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('Pune', 'Pune'), ('Jaipur', 'Jaipur'), ('Lucknow', 'Lucknow'), ('Ahmedabad', 'Ahmedabad')], max_length=100)),
                ('rental_price_hourly', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('rental_price_daily', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('color', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Fair', 'Fair')], default='Good', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bike_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['city', 'bike_type'], name='bikes_bike_city_29b1dc_idx'), models.Index(fields=['is_available'], name='bikes_bike_is_avai_971b5d_idx')],
            },
        ),
    ]
