# Generated by Django 6.0.3 on 2026-04-06 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
        ('config', '__first__'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bike',
            name='bikes_bike_city_29b1dc_idx',
        ),
        migrations.AddField(
            model_name='bike',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='config.location'),
        ),
        migrations.AddIndex(
            model_name='bike',
            index=models.Index(fields=['location', 'bike_type'], name='bikes_bike_locatio_b685df_idx'),
        ),
        migrations.RemoveField(
            model_name='bike',
            name='city',
        ),
    ]
