# Generated by Django 6.0.3 on 2026-04-06 06:18

from django.db import migrations, models
import django.core.validators
from config.models import Location


def create_locations_and_migrate_bikes(apps, schema_editor):
    """Create Location objects and migrate existing bikes to use them"""
    # Get the historical Bike model
    Bike = apps.get_model('bikes', 'Bike')
    
    # Define location data
    locations_data = {
        'Delhi': {
            'description': 'Capital city of India',
            'icon': '🏛️',
            'color': '#FF6B6B',
            'latitude': 28.7041,
            'longitude': 77.1025,
        },
        'Mumbai': {
            'description': 'Financial capital of India',
            'icon': '🌆',
            'color': '#4ECDC4',
            'latitude': 19.0760,
            'longitude': 72.8777,
        },
        'Bangalore': {
            'description': 'Silicon Valley of India',
            'icon': '🏢',
            'color': '#45B7D1',
            'latitude': 12.9716,
            'longitude': 77.5946,
        },
    }
    
    # Create Location objects
    locations = {}
    for city_name, data in locations_data.items():
        location, created = Location.objects.get_or_create(
            name=city_name,
            defaults={
                'description': data['description'],
                'icon': data['icon'],
                'color': data['color'],
                'latitude': data['latitude'],
                'longitude': data['longitude'],
                'is_active': True,
            }
        )
        locations[city_name] = location
        if created:
            print(f"Created location: {city_name}")
    
    # Update existing bikes to reference locations
    for bike in Bike.objects.all():
        if bike.city and bike.city in locations:
            bike.location = locations[bike.city]
            bike.save()
            print(f"Updated bike '{bike.name}' to location '{bike.city}'")


def reverse_migration(apps, schema_editor):
    """Reverse the migration - set location back to None"""
    Bike = apps.get_model('bikes', 'Bike')
    
    for bike in Bike.objects.all():
        bike.location = None
        bike.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_remove_bike_bikes_bike_city_29b1dc_idx_bike_location_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_locations_and_migrate_bikes,
            reverse_code=reverse_migration
        ),
    ]
